language: node_js
node_js:
  - lts/*
install:
  - pnpm install
script:
  - pnpm docs:build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vitepress/dist
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: main
